// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pixel.proto

package ore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PixelData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where the pixel is, in the recording's own coordinates: signed, fixed to
	// the canvas as the recording started, unaffected by any later resize.
	X      int32   `protobuf:"zigzag32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32   `protobuf:"zigzag32,2,opt,name=y,proto3" json:"y,omitempty"`
	Color  uint32  `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Author *uint64 `protobuf:"varint,4,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Tag    *uint64 `protobuf:"varint,5,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	// Milliseconds *before* the enclosing chunk's timestamp that this pixel
	// was actually placed.
	//
	// A delta is written once per flush and carries every pixel that changed
	// since the last one, so its own timestamp is the flush - not the moment
	// any given pixel was painted. Without this a time-based renderer applies
	// a whole flush window at once, and every pixel in it shares one instant.
	//
	// Relative rather than absolute on purpose: the value is bounded by the
	// flush interval, so it costs 2-3 bytes as a varint where an absolute
	// epoch-ms uint64 costs 7 - and the top 40 bits of that would be identical
	// for every pixel in the file.
	//
	// WRITERS MUST set this whenever the placement time is known and differs
	// from the enclosing chunk's timestamp, and MUST leave it unset otherwise.
	// Unset therefore means exactly one thing - "no better information than
	// the chunk's own timestamp" - and covers every case where there is none:
	//
	//   - the time was never recorded (a pre-v3 recording, or a pixel restored
	//     by a moderator rollback, whose real paint time is long gone);
	//   - the time is a *bound* rather than an instant, i.e. "no later than",
	//     which a keyframe hands down for pixels it has no exact time for;
	//   - the clock moved backwards between the placement and the flush, so
	//     the difference is not a duration.
	//
	// Deliberately `optional` rather than a bare uint32, and it must stay that
	// way: proto3 implicit presence would default it to 0, and 0 is precisely
	// "placed at the chunk's timestamp" - so the four cases above would become
	// indistinguishable from an exact placement, which is a claim the writer
	// cannot make. It costs nothing on the wire either, since an implicit-
	// presence scalar equal to 0 is not serialized at all.
	//
	// Readers must not treat unset as 0. Fall back to the chunk's timestamp
	// and carry the fact that it is a bound (see format.PlacedAt).
	Offset        *uint32 `protobuf:"varint,6,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixelData) Reset() {
	*x = PixelData{}
	mi := &file_pixel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixelData) ProtoMessage() {}

func (x *PixelData) ProtoReflect() protoreflect.Message {
	mi := &file_pixel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixelData.ProtoReflect.Descriptor instead.
func (*PixelData) Descriptor() ([]byte, []int) {
	return file_pixel_proto_rawDescGZIP(), []int{0}
}

func (x *PixelData) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PixelData) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PixelData) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *PixelData) GetAuthor() uint64 {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return 0
}

func (x *PixelData) GetTag() uint64 {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return 0
}

func (x *PixelData) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

var File_pixel_proto protoreflect.FileDescriptor

const file_pixel_proto_rawDesc = "" +
	"\n" +
	"\vpixel.proto\x12\n" +
	"molten.ore\"\xac\x01\n" +
	"\tPixelData\x12\f\n" +
	"\x01x\x18\x01 \x01(\x11R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x11R\x01y\x12\x14\n" +
	"\x05color\x18\x03 \x01(\rR\x05color\x12\x1b\n" +
	"\x06author\x18\x04 \x01(\x04H\x00R\x06author\x88\x01\x01\x12\x15\n" +
	"\x03tag\x18\x05 \x01(\x04H\x01R\x03tag\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x06 \x01(\rH\x02R\x06offset\x88\x01\x01B\t\n" +
	"\a_authorB\x06\n" +
	"\x04_tagB\t\n" +
	"\a_offsetB#Z!github.com/pixelate-it/molten/oreb\x06proto3"

var (
	file_pixel_proto_rawDescOnce sync.Once
	file_pixel_proto_rawDescData []byte
)

func file_pixel_proto_rawDescGZIP() []byte {
	file_pixel_proto_rawDescOnce.Do(func() {
		file_pixel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pixel_proto_rawDesc), len(file_pixel_proto_rawDesc)))
	})
	return file_pixel_proto_rawDescData
}

var file_pixel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pixel_proto_goTypes = []any{
	(*PixelData)(nil), // 0: molten.ore.PixelData
}
var file_pixel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pixel_proto_init() }
func file_pixel_proto_init() {
	if File_pixel_proto != nil {
		return
	}
	file_pixel_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pixel_proto_rawDesc), len(file_pixel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pixel_proto_goTypes,
		DependencyIndexes: file_pixel_proto_depIdxs,
		MessageInfos:      file_pixel_proto_msgTypes,
	}.Build()
	File_pixel_proto = out.File
	file_pixel_proto_goTypes = nil
	file_pixel_proto_depIdxs = nil
}
