// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: record.proto

package ore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*PixelData           `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0}
}

func (x *Delta) GetChanges() []*PixelData {
	if x != nil {
		return x.Changes
	}
	return nil
}

// The canvas' window: how big it is and which part of the plane it covers.
//
// Written as the second chunk of every recording, to open it, and again on
// every change of size or position. A reader that sees one keeps everything it
// holds and moves it into the new window - a coordinate means the same pixel
// on both sides, so there is nothing to re-address and nothing to restate.
//
// It carries no pixels, and that is the whole point of it being its own chunk.
// Until v7 a resize was a Keyframe carrying the entire painted canvas, because
// a pixel was addressed by an offset into the canvas and every offset changed
// when the canvas did - so the reader had to be handed the whole thing again.
// On a real season that cost 91% of the file: 5.05 MB of restatement against
// 0.47 MB of actual history.
//
// Both directions. A cut destroys the pixels outside the new window, and every
// reader has to drop them itself - under the old scheme they were simply
// omitted from the keyframe, which did the same job by accident.
type Resize struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Width  uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// The canvas' top-left corner, in the same signed coordinates a PixelData
	// is named by. Negative once a season has been expanded leftwards or
	// upwards; zero for the opening Resize of every season, since the origin
	// is defined as the corner the canvas starts on.
	//
	// A size alone never located a canvas. That was invisible while a pixel
	// carried an offset into it - an offset has nowhere else to point - and
	// became load-bearing the moment a pixel started naming a place on the
	// plane.
	MinX          int32 `protobuf:"zigzag32,3,opt,name=min_x,json=minX,proto3" json:"min_x,omitempty"`
	MinY          int32 `protobuf:"zigzag32,4,opt,name=min_y,json=minY,proto3" json:"min_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{1}
}

func (x *Resize) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resize) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Resize) GetMinX() int32 {
	if x != nil {
		return x.MinX
	}
	return 0
}

func (x *Resize) GetMinY() int32 {
	if x != nil {
		return x.MinY
	}
	return 0
}

// A restatement of canvas contents: these pixels are what is there, now.
//
// Carries no geometry and never changes the canvas' window - that is what
// Resize is for. Applying one is exactly applying a Delta whose changes happen
// to describe every painted pixel rather than the ones that just moved.
//
// **Nothing writes one today.** It is kept because the format is otherwise a
// pure delta log from byte 0, and a periodic snapshot is the obvious thing to
// add if that ever needs a recovery point. A reader should implement it
// anyway; it costs the same five lines as a Delta.
type Keyframe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pixels        []*PixelData           `protobuf:"bytes,1,rep,name=pixels,proto3" json:"pixels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keyframe) Reset() {
	*x = Keyframe{}
	mi := &file_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keyframe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keyframe) ProtoMessage() {}

func (x *Keyframe) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keyframe.ProtoReflect.Descriptor instead.
func (*Keyframe) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{2}
}

func (x *Keyframe) GetPixels() []*PixelData {
	if x != nil {
		return x.Pixels
	}
	return nil
}

// Seals a recording: written once, as the last chunk, when the season it
// records is over. Its presence is the only thing that distinguishes a
// finished recording from one whose writer is still running or died mid-flush
// - the framing alone cannot, since both simply end after a valid chunk.
type Footer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pixel changes recorded across every Delta in the file. Deliberately not
	// a chunk count, and deliberately not counting Keyframe pixels: a keyframe
	// restates pixels that were already counted when their delta was written.
	TotalPixelsPlaced uint64 `protobuf:"varint,1,opt,name=total_pixels_placed,json=totalPixelsPlaced,proto3" json:"total_pixels_placed,omitempty"`
	// xxHash64 (seed 0) over the canvas as of this footer, digesting every
	// non-blank pixel sorted by (y, x) as a 12-byte little-endian record:
	// int32 x, int32 y, uint32 color (0x00RRGGBB).
	//
	// The coordinates are the pixels' own, which is what makes the same
	// artwork digest the same either side of a resize. That used to need
	// saying, back when a pixel was addressed by an offset into the canvas.
	//
	// Non-cryptographic: this catches a reader implementation (Go, C, the
	// TypeScript writer) that disagrees about what the file means, not an
	// attacker who is free to rewrite the footer along with the chunks.
	CanvasChecksum uint64 `protobuf:"varint,2,opt,name=canvas_checksum,json=canvasChecksum,proto3" json:"canvas_checksum,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Footer) Reset() {
	*x = Footer{}
	mi := &file_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Footer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Footer) ProtoMessage() {}

func (x *Footer) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Footer.ProtoReflect.Descriptor instead.
func (*Footer) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{3}
}

func (x *Footer) GetTotalPixelsPlaced() uint64 {
	if x != nil {
		return x.TotalPixelsPlaced
	}
	return 0
}

func (x *Footer) GetCanvasChecksum() uint64 {
	if x != nil {
		return x.CanvasChecksum
	}
	return 0
}

type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The compatibility gate, and load-bearing as of the coordinate change:
	// a reader MUST refuse a version it does not know. Before that it was a
	// diagnostic nothing branched on, which left an older binary free to read
	// a newer file and lay every pixel out against an addressing the file no
	// longer uses - wrong, and only visibly so once somebody watched the
	// render.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Season name.
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	StartedAt uint64 `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Parameters of the game this recording belongs to. Everything that is
	// fixed for the whole recording goes here; anything that can change
	// mid-recording (i.e. the canvas size) does not.
	GameId        *uint64 `protobuf:"varint,6,opt,name=game_id,json=gameId,proto3,oneof" json:"game_id,omitempty"`
	Cooldown      *uint32 `protobuf:"varint,7,opt,name=cooldown,proto3,oneof" json:"cooldown,omitempty"`
	EndsAt        *uint64 `protobuf:"varint,8,opt,name=ends_at,json=endsAt,proto3,oneof" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{4}
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetStartedAt() uint64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Header) GetGameId() uint64 {
	if x != nil && x.GameId != nil {
		return *x.GameId
	}
	return 0
}

func (x *Header) GetCooldown() uint32 {
	if x != nil && x.Cooldown != nil {
		return *x.Cooldown
	}
	return 0
}

func (x *Header) GetEndsAt() uint64 {
	if x != nil && x.EndsAt != nil {
		return *x.EndsAt
	}
	return 0
}

type RecordingChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When this chunk was written, in epoch milliseconds.
	//
	// On the chunk rather than on each payload, where it used to be repeated
	// five times over. Every chunk has one, and a field every member of a
	// union carries belongs to the union - but the reason it moved is that a
	// reader can now ask *when* without asking *what*. Walking a season to
	// build an index of times against byte offsets no longer means decoding
	// the payload at every step.
	//
	// Zero means unknown, which is the only honest reading of a chunk that
	// never carried one; readers do not treat it as the epoch.
	//
	// `Header.started_at` is deliberately not this. That is the *season's*
	// start; this is when the header was written, and a recording rolled
	// mid-season - after a seal, or after a crash - has the two several days
	// apart. Until now there was nowhere to say so.
	Timestamp uint64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Field 2 was used once by the original prototype and reserved ever since.
	// Reusing a reserved number is normally how you produce a file that decodes
	// into the wrong message - but a reader refuses any version it does not
	// know (see Header.version), and no pre-v7 chunk is ever handed to this
	// dispatch. The gate is what makes the number free again.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*RecordingChunk_Header
	//	*RecordingChunk_Resize
	//	*RecordingChunk_Keyframe
	//	*RecordingChunk_Delta
	//	*RecordingChunk_Footer
	Payload       isRecordingChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingChunk) Reset() {
	*x = RecordingChunk{}
	mi := &file_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingChunk) ProtoMessage() {}

func (x *RecordingChunk) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingChunk.ProtoReflect.Descriptor instead.
func (*RecordingChunk) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{5}
}

func (x *RecordingChunk) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RecordingChunk) GetPayload() isRecordingChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RecordingChunk) GetHeader() *Header {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *RecordingChunk) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *RecordingChunk) GetKeyframe() *Keyframe {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Keyframe); ok {
			return x.Keyframe
		}
	}
	return nil
}

func (x *RecordingChunk) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *RecordingChunk) GetFooter() *Footer {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Footer); ok {
			return x.Footer
		}
	}
	return nil
}

type isRecordingChunk_Payload interface {
	isRecordingChunk_Payload()
}

type RecordingChunk_Header struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type RecordingChunk_Resize struct {
	Resize *Resize `protobuf:"bytes,2,opt,name=resize,proto3,oneof"`
}

type RecordingChunk_Keyframe struct {
	Keyframe *Keyframe `protobuf:"bytes,3,opt,name=keyframe,proto3,oneof"`
}

type RecordingChunk_Delta struct {
	Delta *Delta `protobuf:"bytes,4,opt,name=delta,proto3,oneof"`
}

type RecordingChunk_Footer struct {
	Footer *Footer `protobuf:"bytes,5,opt,name=footer,proto3,oneof"`
}

func (*RecordingChunk_Header) isRecordingChunk_Payload() {}

func (*RecordingChunk_Resize) isRecordingChunk_Payload() {}

func (*RecordingChunk_Keyframe) isRecordingChunk_Payload() {}

func (*RecordingChunk_Delta) isRecordingChunk_Payload() {}

func (*RecordingChunk_Footer) isRecordingChunk_Payload() {}

var File_record_proto protoreflect.FileDescriptor

const file_record_proto_rawDesc = "" +
	"\n" +
	"\frecord.proto\x12\n" +
	"molten.ore\x1a\vpixel.proto\"8\n" +
	"\x05Delta\x12/\n" +
	"\achanges\x18\x01 \x03(\v2\x15.molten.ore.PixelDataR\achanges\"`\n" +
	"\x06Resize\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x13\n" +
	"\x05min_x\x18\x03 \x01(\x11R\x04minX\x12\x13\n" +
	"\x05min_y\x18\x04 \x01(\x11R\x04minY\"9\n" +
	"\bKeyframe\x12-\n" +
	"\x06pixels\x18\x01 \x03(\v2\x15.molten.ore.PixelDataR\x06pixels\"a\n" +
	"\x06Footer\x12.\n" +
	"\x13total_pixels_placed\x18\x01 \x01(\x04R\x11totalPixelsPlaced\x12'\n" +
	"\x0fcanvas_checksum\x18\x02 \x01(\x04R\x0ecanvasChecksum\"\xf2\x01\n" +
	"\x06Header\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x04R\tstartedAt\x12\x1c\n" +
	"\agame_id\x18\x06 \x01(\x04H\x00R\x06gameId\x88\x01\x01\x12\x1f\n" +
	"\bcooldown\x18\a \x01(\rH\x01R\bcooldown\x88\x01\x01\x12\x1c\n" +
	"\aends_at\x18\b \x01(\x04H\x02R\x06endsAt\x88\x01\x01B\n" +
	"\n" +
	"\b_game_idB\v\n" +
	"\t_cooldownB\n" +
	"\n" +
	"\b_ends_atJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x05widthR\x06height\"\xa2\x02\n" +
	"\x0eRecordingChunk\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x12.molten.ore.HeaderH\x00R\x06header\x12,\n" +
	"\x06resize\x18\x02 \x01(\v2\x12.molten.ore.ResizeH\x00R\x06resize\x122\n" +
	"\bkeyframe\x18\x03 \x01(\v2\x14.molten.ore.KeyframeH\x00R\bkeyframe\x12)\n" +
	"\x05delta\x18\x04 \x01(\v2\x11.molten.ore.DeltaH\x00R\x05delta\x12,\n" +
	"\x06footer\x18\x05 \x01(\v2\x12.molten.ore.FooterH\x00R\x06footerB\t\n" +
	"\apayloadB#Z!github.com/pixelate-it/molten/oreb\x06proto3"

var (
	file_record_proto_rawDescOnce sync.Once
	file_record_proto_rawDescData []byte
)

func file_record_proto_rawDescGZIP() []byte {
	file_record_proto_rawDescOnce.Do(func() {
		file_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_record_proto_rawDesc), len(file_record_proto_rawDesc)))
	})
	return file_record_proto_rawDescData
}

var file_record_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_record_proto_goTypes = []any{
	(*Delta)(nil),          // 0: molten.ore.Delta
	(*Resize)(nil),         // 1: molten.ore.Resize
	(*Keyframe)(nil),       // 2: molten.ore.Keyframe
	(*Footer)(nil),         // 3: molten.ore.Footer
	(*Header)(nil),         // 4: molten.ore.Header
	(*RecordingChunk)(nil), // 5: molten.ore.RecordingChunk
	(*PixelData)(nil),      // 6: molten.ore.PixelData
}
var file_record_proto_depIdxs = []int32{
	6, // 0: molten.ore.Delta.changes:type_name -> molten.ore.PixelData
	6, // 1: molten.ore.Keyframe.pixels:type_name -> molten.ore.PixelData
	4, // 2: molten.ore.RecordingChunk.header:type_name -> molten.ore.Header
	1, // 3: molten.ore.RecordingChunk.resize:type_name -> molten.ore.Resize
	2, // 4: molten.ore.RecordingChunk.keyframe:type_name -> molten.ore.Keyframe
	0, // 5: molten.ore.RecordingChunk.delta:type_name -> molten.ore.Delta
	3, // 6: molten.ore.RecordingChunk.footer:type_name -> molten.ore.Footer
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_record_proto_init() }
func file_record_proto_init() {
	if File_record_proto != nil {
		return
	}
	file_pixel_proto_init()
	file_record_proto_msgTypes[4].OneofWrappers = []any{}
	file_record_proto_msgTypes[5].OneofWrappers = []any{
		(*RecordingChunk_Header)(nil),
		(*RecordingChunk_Resize)(nil),
		(*RecordingChunk_Keyframe)(nil),
		(*RecordingChunk_Delta)(nil),
		(*RecordingChunk_Footer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_record_proto_rawDesc), len(file_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_proto_goTypes,
		DependencyIndexes: file_record_proto_depIdxs,
		MessageInfos:      file_record_proto_msgTypes,
	}.Build()
	File_record_proto = out.File
	file_record_proto_goTypes = nil
	file_record_proto_depIdxs = nil
}
