// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: record.proto

package ore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Changes       []*PixelData           `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0}
}

func (x *Delta) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Delta) GetChanges() []*PixelData {
	if x != nil {
		return x.Changes
	}
	return nil
}

type Keyframe struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pixels    []*PixelData           `protobuf:"bytes,2,rep,name=pixels,proto3" json:"pixels,omitempty"`
	// Present together or not at all, and their presence is the format's only
	// resize signal: a reader that sees them blanks its canvas at the new size
	// before applying `pixels`, so a keyframe carrying them MUST carry
	// everything that survives the resize.
	//
	// The recording's opening keyframe - the second chunk, always - is
	// required to carry them. It is what establishes the canvas size, since
	// the Header no longer can (see the reserved fields there).
	//
	// Absent on any other keyframe, which is then a plain restatement of
	// canvas contents at the current size. Note the writer emits no periodic
	// keyframes: repeated full-canvas snapshots dominated the file size for
	// something no reader consumed.
	Width  *uint32 `protobuf:"varint,3,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height *uint32 `protobuf:"varint,4,opt,name=height,proto3,oneof" json:"height,omitempty"`
	// The canvas' top-left corner, in the same signed coordinates a PixelData
	// is named by, and carried under the same rule as width and height: with
	// them or not at all.
	//
	// A size alone never said where the canvas was. Before pixels carried
	// coordinates that was hidden, because a pixel's id was an offset into the
	// canvas and so could only mean a place inside it; the corner rode along
	// as `origin_x`/`origin_y`, phrased as a translation to undo. Now that a
	// pixel names a place on the plane, the canvas has to name the part of the
	// plane it covers, or a reader given a sparse keyframe - white pixels are
	// skipped - has no way to work out which region those pixels sit in.
	//
	// Absent means zero, which is right for the opening keyframe of every
	// season: the origin is defined as the canvas' corner at the start.
	MinX          *int32 `protobuf:"zigzag32,5,opt,name=min_x,json=minX,proto3,oneof" json:"min_x,omitempty"`
	MinY          *int32 `protobuf:"zigzag32,6,opt,name=min_y,json=minY,proto3,oneof" json:"min_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keyframe) Reset() {
	*x = Keyframe{}
	mi := &file_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keyframe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keyframe) ProtoMessage() {}

func (x *Keyframe) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keyframe.ProtoReflect.Descriptor instead.
func (*Keyframe) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{1}
}

func (x *Keyframe) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Keyframe) GetPixels() []*PixelData {
	if x != nil {
		return x.Pixels
	}
	return nil
}

func (x *Keyframe) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Keyframe) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *Keyframe) GetMinX() int32 {
	if x != nil && x.MinX != nil {
		return *x.MinX
	}
	return 0
}

func (x *Keyframe) GetMinY() int32 {
	if x != nil && x.MinY != nil {
		return *x.MinY
	}
	return 0
}

// Seals a recording: written once, as the last chunk, when the season it
// records is over. Its presence is the only thing that distinguishes a
// finished recording from one whose writer is still running or died mid-flush
// - the framing alone cannot, since both simply end after a valid chunk.
type Footer struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Pixel changes recorded across every Delta in the file. Deliberately not
	// a chunk count and deliberately not counting Keyframe pixels: a keyframe
	// restates pixels that were already counted when their delta was written.
	TotalPixelsPlaced uint64 `protobuf:"varint,2,opt,name=total_pixels_placed,json=totalPixelsPlaced,proto3" json:"total_pixels_placed,omitempty"`
	// xxHash64 (seed 0) over the canvas as of this footer, digesting every
	// non-blank pixel sorted by (y, x) as a 12-byte little-endian record:
	// int32 x, int32 y, uint32 color (0x00RRGGBB).
	//
	// The coordinates are the pixels' own, which is what makes the same
	// artwork digest the same either side of a resize. That used to need
	// saying, back when a pixel was addressed by an offset into the canvas.
	//
	// Non-cryptographic: this catches a reader implementation (Go, C, the
	// TypeScript writer) that disagrees about what the file means, not an
	// attacker who is free to rewrite the footer along with the chunks.
	CanvasChecksum uint64 `protobuf:"varint,3,opt,name=canvas_checksum,json=canvasChecksum,proto3" json:"canvas_checksum,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Footer) Reset() {
	*x = Footer{}
	mi := &file_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Footer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Footer) ProtoMessage() {}

func (x *Footer) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Footer.ProtoReflect.Descriptor instead.
func (*Footer) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{2}
}

func (x *Footer) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Footer) GetTotalPixelsPlaced() uint64 {
	if x != nil {
		return x.TotalPixelsPlaced
	}
	return 0
}

func (x *Footer) GetCanvasChecksum() uint64 {
	if x != nil {
		return x.CanvasChecksum
	}
	return 0
}

type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The compatibility gate, and load-bearing as of the coordinate change:
	// a reader MUST refuse a version it does not know. Before that it was a
	// diagnostic nothing branched on, which left an older binary free to read
	// a newer file and lay every pixel out against an addressing the file no
	// longer uses - wrong, and only visibly so once somebody watched the
	// render.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Season name.
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	StartedAt uint64 `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Parameters of the game this recording belongs to. Everything that is
	// fixed for the whole recording goes here; anything that can change
	// mid-recording (i.e. the canvas size) does not.
	GameId        *uint64 `protobuf:"varint,6,opt,name=game_id,json=gameId,proto3,oneof" json:"game_id,omitempty"`
	Cooldown      *uint32 `protobuf:"varint,7,opt,name=cooldown,proto3,oneof" json:"cooldown,omitempty"`
	EndsAt        *uint64 `protobuf:"varint,8,opt,name=ends_at,json=endsAt,proto3,oneof" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{3}
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetStartedAt() uint64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Header) GetGameId() uint64 {
	if x != nil && x.GameId != nil {
		return *x.GameId
	}
	return 0
}

func (x *Header) GetCooldown() uint32 {
	if x != nil && x.Cooldown != nil {
		return *x.Cooldown
	}
	return 0
}

func (x *Header) GetEndsAt() uint64 {
	if x != nil && x.EndsAt != nil {
		return *x.EndsAt
	}
	return 0
}

type RecordingChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RecordingChunk_Header
	//	*RecordingChunk_Keyframe
	//	*RecordingChunk_Delta
	//	*RecordingChunk_Footer
	Payload       isRecordingChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingChunk) Reset() {
	*x = RecordingChunk{}
	mi := &file_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingChunk) ProtoMessage() {}

func (x *RecordingChunk) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingChunk.ProtoReflect.Descriptor instead.
func (*RecordingChunk) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{4}
}

func (x *RecordingChunk) GetPayload() isRecordingChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RecordingChunk) GetHeader() *Header {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *RecordingChunk) GetKeyframe() *Keyframe {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Keyframe); ok {
			return x.Keyframe
		}
	}
	return nil
}

func (x *RecordingChunk) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *RecordingChunk) GetFooter() *Footer {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Footer); ok {
			return x.Footer
		}
	}
	return nil
}

type isRecordingChunk_Payload interface {
	isRecordingChunk_Payload()
}

type RecordingChunk_Header struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type RecordingChunk_Keyframe struct {
	Keyframe *Keyframe `protobuf:"bytes,3,opt,name=keyframe,proto3,oneof"`
}

type RecordingChunk_Delta struct {
	Delta *Delta `protobuf:"bytes,4,opt,name=delta,proto3,oneof"`
}

type RecordingChunk_Footer struct {
	Footer *Footer `protobuf:"bytes,5,opt,name=footer,proto3,oneof"`
}

func (*RecordingChunk_Header) isRecordingChunk_Payload() {}

func (*RecordingChunk_Keyframe) isRecordingChunk_Payload() {}

func (*RecordingChunk_Delta) isRecordingChunk_Payload() {}

func (*RecordingChunk_Footer) isRecordingChunk_Payload() {}

var File_record_proto protoreflect.FileDescriptor

const file_record_proto_rawDesc = "" +
	"\n" +
	"\frecord.proto\x12\n" +
	"molten.ore\x1a\vpixel.proto\"V\n" +
	"\x05Delta\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12/\n" +
	"\achanges\x18\x02 \x03(\v2\x15.molten.ore.PixelDataR\achanges\"\xec\x01\n" +
	"\bKeyframe\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12-\n" +
	"\x06pixels\x18\x02 \x03(\v2\x15.molten.ore.PixelDataR\x06pixels\x12\x19\n" +
	"\x05width\x18\x03 \x01(\rH\x00R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\x04 \x01(\rH\x01R\x06height\x88\x01\x01\x12\x18\n" +
	"\x05min_x\x18\x05 \x01(\x11H\x02R\x04minX\x88\x01\x01\x12\x18\n" +
	"\x05min_y\x18\x06 \x01(\x11H\x03R\x04minY\x88\x01\x01B\b\n" +
	"\x06_widthB\t\n" +
	"\a_heightB\b\n" +
	"\x06_min_xB\b\n" +
	"\x06_min_y\"\x7f\n" +
	"\x06Footer\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12.\n" +
	"\x13total_pixels_placed\x18\x02 \x01(\x04R\x11totalPixelsPlaced\x12'\n" +
	"\x0fcanvas_checksum\x18\x03 \x01(\x04R\x0ecanvasChecksum\"\xf2\x01\n" +
	"\x06Header\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x04R\tstartedAt\x12\x1c\n" +
	"\agame_id\x18\x06 \x01(\x04H\x00R\x06gameId\x88\x01\x01\x12\x1f\n" +
	"\bcooldown\x18\a \x01(\rH\x01R\bcooldown\x88\x01\x01\x12\x1c\n" +
	"\aends_at\x18\b \x01(\x04H\x02R\x06endsAt\x88\x01\x01B\n" +
	"\n" +
	"\b_game_idB\v\n" +
	"\t_cooldownB\n" +
	"\n" +
	"\b_ends_atJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x05widthR\x06height\"\xdc\x01\n" +
	"\x0eRecordingChunk\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x12.molten.ore.HeaderH\x00R\x06header\x122\n" +
	"\bkeyframe\x18\x03 \x01(\v2\x14.molten.ore.KeyframeH\x00R\bkeyframe\x12)\n" +
	"\x05delta\x18\x04 \x01(\v2\x11.molten.ore.DeltaH\x00R\x05delta\x12,\n" +
	"\x06footer\x18\x05 \x01(\v2\x12.molten.ore.FooterH\x00R\x06footerB\t\n" +
	"\apayloadJ\x04\b\x02\x10\x03B#Z!github.com/pixelate-it/molten/oreb\x06proto3"

var (
	file_record_proto_rawDescOnce sync.Once
	file_record_proto_rawDescData []byte
)

func file_record_proto_rawDescGZIP() []byte {
	file_record_proto_rawDescOnce.Do(func() {
		file_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_record_proto_rawDesc), len(file_record_proto_rawDesc)))
	})
	return file_record_proto_rawDescData
}

var file_record_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_record_proto_goTypes = []any{
	(*Delta)(nil),          // 0: molten.ore.Delta
	(*Keyframe)(nil),       // 1: molten.ore.Keyframe
	(*Footer)(nil),         // 2: molten.ore.Footer
	(*Header)(nil),         // 3: molten.ore.Header
	(*RecordingChunk)(nil), // 4: molten.ore.RecordingChunk
	(*PixelData)(nil),      // 5: molten.ore.PixelData
}
var file_record_proto_depIdxs = []int32{
	5, // 0: molten.ore.Delta.changes:type_name -> molten.ore.PixelData
	5, // 1: molten.ore.Keyframe.pixels:type_name -> molten.ore.PixelData
	3, // 2: molten.ore.RecordingChunk.header:type_name -> molten.ore.Header
	1, // 3: molten.ore.RecordingChunk.keyframe:type_name -> molten.ore.Keyframe
	0, // 4: molten.ore.RecordingChunk.delta:type_name -> molten.ore.Delta
	2, // 5: molten.ore.RecordingChunk.footer:type_name -> molten.ore.Footer
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_record_proto_init() }
func file_record_proto_init() {
	if File_record_proto != nil {
		return
	}
	file_pixel_proto_init()
	file_record_proto_msgTypes[1].OneofWrappers = []any{}
	file_record_proto_msgTypes[3].OneofWrappers = []any{}
	file_record_proto_msgTypes[4].OneofWrappers = []any{
		(*RecordingChunk_Header)(nil),
		(*RecordingChunk_Keyframe)(nil),
		(*RecordingChunk_Delta)(nil),
		(*RecordingChunk_Footer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_record_proto_rawDesc), len(file_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_proto_goTypes,
		DependencyIndexes: file_record_proto_depIdxs,
		MessageInfos:      file_record_proto_msgTypes,
	}.Build()
	File_record_proto = out.File
	file_record_proto_goTypes = nil
	file_record_proto_depIdxs = nil
}
