// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: record.proto

package ore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Changes       []*PixelData           `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0}
}

func (x *Delta) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Delta) GetChanges() []*PixelData {
	if x != nil {
		return x.Changes
	}
	return nil
}

type Keyframe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pixels        []*PixelData           `protobuf:"bytes,2,rep,name=pixels,proto3" json:"pixels,omitempty"`
	Width         *uint32                `protobuf:"varint,3,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height        *uint32                `protobuf:"varint,4,opt,name=height,proto3,oneof" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keyframe) Reset() {
	*x = Keyframe{}
	mi := &file_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keyframe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keyframe) ProtoMessage() {}

func (x *Keyframe) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keyframe.ProtoReflect.Descriptor instead.
func (*Keyframe) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{1}
}

func (x *Keyframe) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Keyframe) GetPixels() []*PixelData {
	if x != nil {
		return x.Pixels
	}
	return nil
}

func (x *Keyframe) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Keyframe) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type Header struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// reserved 2, 3;
	// reserved "width", "height";
	Width         *uint32 `protobuf:"varint,2,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height        *uint32 `protobuf:"varint,3,opt,name=height,proto3,oneof" json:"height,omitempty"`
	Name          string  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	StartedAt     uint64  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Header) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetStartedAt() uint64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type RecordingChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RecordingChunk_Header
	//	*RecordingChunk_Keyframe
	//	*RecordingChunk_Delta
	Payload       isRecordingChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingChunk) Reset() {
	*x = RecordingChunk{}
	mi := &file_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingChunk) ProtoMessage() {}

func (x *RecordingChunk) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingChunk.ProtoReflect.Descriptor instead.
func (*RecordingChunk) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{3}
}

func (x *RecordingChunk) GetPayload() isRecordingChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RecordingChunk) GetHeader() *Header {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *RecordingChunk) GetKeyframe() *Keyframe {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Keyframe); ok {
			return x.Keyframe
		}
	}
	return nil
}

func (x *RecordingChunk) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Payload.(*RecordingChunk_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

type isRecordingChunk_Payload interface {
	isRecordingChunk_Payload()
}

type RecordingChunk_Header struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type RecordingChunk_Keyframe struct {
	Keyframe *Keyframe `protobuf:"bytes,3,opt,name=keyframe,proto3,oneof"`
}

type RecordingChunk_Delta struct {
	Delta *Delta `protobuf:"bytes,4,opt,name=delta,proto3,oneof"`
}

func (*RecordingChunk_Header) isRecordingChunk_Payload() {}

func (*RecordingChunk_Keyframe) isRecordingChunk_Payload() {}

func (*RecordingChunk_Delta) isRecordingChunk_Payload() {}

var File_record_proto protoreflect.FileDescriptor

const file_record_proto_rawDesc = "" +
	"\n" +
	"\frecord.proto\x12\n" +
	"molten.ore\x1a\x10pixel_data.proto\"V\n" +
	"\x05Delta\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12/\n" +
	"\achanges\x18\x02 \x03(\v2\x15.molten.ore.PixelDataR\achanges\"\xa4\x01\n" +
	"\bKeyframe\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12-\n" +
	"\x06pixels\x18\x02 \x03(\v2\x15.molten.ore.PixelDataR\x06pixels\x12\x19\n" +
	"\x05width\x18\x03 \x01(\rH\x00R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\x04 \x01(\rH\x01R\x06height\x88\x01\x01B\b\n" +
	"\x06_widthB\t\n" +
	"\a_height\"\xa2\x01\n" +
	"\x06Header\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x19\n" +
	"\x05width\x18\x02 \x01(\rH\x00R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\x03 \x01(\rH\x01R\x06height\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x04R\tstartedAtB\b\n" +
	"\x06_widthB\t\n" +
	"\a_height\"\xae\x01\n" +
	"\x0eRecordingChunk\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x12.molten.ore.HeaderH\x00R\x06header\x122\n" +
	"\bkeyframe\x18\x03 \x01(\v2\x14.molten.ore.KeyframeH\x00R\bkeyframe\x12)\n" +
	"\x05delta\x18\x04 \x01(\v2\x11.molten.ore.DeltaH\x00R\x05deltaB\t\n" +
	"\apayloadJ\x04\b\x02\x10\x03B#Z!github.com/pixelate-it/molten/oreb\x06proto3"

var (
	file_record_proto_rawDescOnce sync.Once
	file_record_proto_rawDescData []byte
)

func file_record_proto_rawDescGZIP() []byte {
	file_record_proto_rawDescOnce.Do(func() {
		file_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_record_proto_rawDesc), len(file_record_proto_rawDesc)))
	})
	return file_record_proto_rawDescData
}

var file_record_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_record_proto_goTypes = []any{
	(*Delta)(nil),          // 0: molten.ore.Delta
	(*Keyframe)(nil),       // 1: molten.ore.Keyframe
	(*Header)(nil),         // 2: molten.ore.Header
	(*RecordingChunk)(nil), // 3: molten.ore.RecordingChunk
	(*PixelData)(nil),      // 4: molten.ore.PixelData
}
var file_record_proto_depIdxs = []int32{
	4, // 0: molten.ore.Delta.changes:type_name -> molten.ore.PixelData
	4, // 1: molten.ore.Keyframe.pixels:type_name -> molten.ore.PixelData
	2, // 2: molten.ore.RecordingChunk.header:type_name -> molten.ore.Header
	1, // 3: molten.ore.RecordingChunk.keyframe:type_name -> molten.ore.Keyframe
	0, // 4: molten.ore.RecordingChunk.delta:type_name -> molten.ore.Delta
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_record_proto_init() }
func file_record_proto_init() {
	if File_record_proto != nil {
		return
	}
	file_pixel_data_proto_init()
	file_record_proto_msgTypes[1].OneofWrappers = []any{}
	file_record_proto_msgTypes[2].OneofWrappers = []any{}
	file_record_proto_msgTypes[3].OneofWrappers = []any{
		(*RecordingChunk_Header)(nil),
		(*RecordingChunk_Keyframe)(nil),
		(*RecordingChunk_Delta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_record_proto_rawDesc), len(file_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_proto_goTypes,
		DependencyIndexes: file_record_proto_depIdxs,
		MessageInfos:      file_record_proto_msgTypes,
	}.Build()
	File_record_proto = out.File
	file_record_proto_goTypes = nil
	file_record_proto_depIdxs = nil
}
