// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pixel_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PixelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Color         uint32                 `protobuf:"varint,2,opt,name=color,proto3" json:"color,omitempty"`
	Author        *uint64                `protobuf:"varint,3,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Tag           *uint64                `protobuf:"varint,4,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixelData) Reset() {
	*x = PixelData{}
	mi := &file_pixel_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixelData) ProtoMessage() {}

func (x *PixelData) ProtoReflect() protoreflect.Message {
	mi := &file_pixel_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixelData.ProtoReflect.Descriptor instead.
func (*PixelData) Descriptor() ([]byte, []int) {
	return file_pixel_data_proto_rawDescGZIP(), []int{0}
}

func (x *PixelData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PixelData) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *PixelData) GetAuthor() uint64 {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return 0
}

func (x *PixelData) GetTag() uint64 {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return 0
}

var File_pixel_data_proto protoreflect.FileDescriptor

const file_pixel_data_proto_rawDesc = "" +
	"\n" +
	"\x10pixel_data.proto\x12\x13molten.proto.record\"x\n" +
	"\tPixelData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05color\x18\x02 \x01(\rR\x05color\x12\x1b\n" +
	"\x06author\x18\x03 \x01(\x04H\x00R\x06author\x88\x01\x01\x12\x15\n" +
	"\x03tag\x18\x04 \x01(\x04H\x01R\x03tag\x88\x01\x01B\t\n" +
	"\a_authorB\x06\n" +
	"\x04_tagB%Z#github.com/pixelate-it/molten/protob\x06proto3"

var (
	file_pixel_data_proto_rawDescOnce sync.Once
	file_pixel_data_proto_rawDescData []byte
)

func file_pixel_data_proto_rawDescGZIP() []byte {
	file_pixel_data_proto_rawDescOnce.Do(func() {
		file_pixel_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pixel_data_proto_rawDesc), len(file_pixel_data_proto_rawDesc)))
	})
	return file_pixel_data_proto_rawDescData
}

var file_pixel_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pixel_data_proto_goTypes = []any{
	(*PixelData)(nil), // 0: molten.proto.record.PixelData
}
var file_pixel_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pixel_data_proto_init() }
func file_pixel_data_proto_init() {
	if File_pixel_data_proto != nil {
		return
	}
	file_pixel_data_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pixel_data_proto_rawDesc), len(file_pixel_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pixel_data_proto_goTypes,
		DependencyIndexes: file_pixel_data_proto_depIdxs,
		MessageInfos:      file_pixel_data_proto_msgTypes,
	}.Build()
	File_pixel_data_proto = out.File
	file_pixel_data_proto_goTypes = nil
	file_pixel_data_proto_depIdxs = nil
}
