syntax = "proto3";

package molten.proto.record;
option go_package = "github.com/pixelate-it/molten/proto";

import "pixel_data.proto";

message Delta {
    uint64 timestamp = 1;
    repeated PixelData changes = 2;
}

message Keyframe {
    uint64 timestamp = 1;
    repeated PixelData pixels = 2;
}

message Resize {
    uint64 timestamp = 1;
    uint32 width = 2;
    uint32 height = 3;
}

message Header {
    uint32 version = 1;
    reserved 2, 3;
    reserved "width", "height";
    string name = 4;
    uint64 started_at = 5;
}

message RecordingChunk {
    oneof payload {
        Header header = 1;
        Resize resize = 2;
        Keyframe keyframe = 3;
        Delta delta = 4;
    }
}
